version: '3'

services:

 # ---------------------------------
 # laravelを動かすコンテナ
 # ---------------------------------
 app:
   ports:
     - "80:80"
   build: ./docker/app
   container_name: number-one-rookie
   volumes:
     - ./src:/var/www/html

# ----------------------------------
# MySQLを動かすコンテナ
# ----------------------------------
 db:
   # Docker HubからMySQL5.7の公式イメージをダウンロードしてくる指定
   image: mysql:5.7
   container_name: laravel_db

   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: starbucks_db
     MYSQL_USER: laravel_user
     MYSQL_PASSWORD: laravel_pass
     TZ: 'Asia/Tokyo'

   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306

# ----------------------------------
# phpMyAdminを動かすコンテナ
# ----------------------------------
 phpmyadmin:
  # Docker Hubからイメージをダウンロード
  image: phpmyadmin/phpmyadmin:5

  # コンテナの名前
  container_name: phpmyadmin

  # コンテナと他のサービスを繋げる
  links:
     - db

  # localhost:8080 で phpmyadmin の管理画面にアクセス
  ports:
     - 8080:80

  # セッション情報をボリュームに設定して永続化
  volumes:
     - ./docker/phpmyadmin/sessions:/sessions
